// Generated by CoffeeScript 1.7.1
var escapedTag, react_dom, tagParser, taglist,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

react_dom = require('react').DOM;

tagParser = /_?this\.([\w|_]*)\(/g;

escapedTag = /[\w]*_$/;

taglist = null;

module.exports = function(source, blacklist) {
  if (blacklist == null) {
    blacklist = [];
  }
  taglist = [];
  return source.replace(tagParser, function(fragment, tag) {
    var shortTag;
    if (__indexOf.call(blacklist, tag) >= 0) {
      return fragment;
    }
    if (escapedTag.test(tag)) {
      shortTag = tag.substring(0, tag.length - 1);
      if (__indexOf.call(blacklist, shortTag) >= 0) {
        if (__indexOf.call(taglist, shortTag) < 0) {
          taglist.push(shortTag);
        }
        return "React.DOM." + shortTag + "(";
      }
    }
    if (react_dom.hasOwnProperty(tag)) {
      if (__indexOf.call(taglist, tag) < 0) {
        taglist.push(tag);
      }
      return "React.DOM." + tag + "(";
    }
    return fragment;
  });
};

module.exports.lastTags = function() {
  return taglist;
};
